#!/usr/bin/env bash
#
# Proves that the native executable publishes the same tool catalogue as the JVM build.
#
# Why this exists: a native image can lose part of the catalogue without failing. The
# outputSchema of every tool is generated by reflection over the @OutputSchema(from=...)
# records, and a record the native image does not know about yields `{"type":"object"}` --
# a valid schema, an empty one, and no error anywhere. A client that validates
# structuredContent then accepts anything, and a typed SDK gets no fields to type. The
# only way to see it is to ask both binaries and compare.
#
# Usage:
#   ./mvnw package -DskipTests                 # JVM build
#   ./mvnw package -Pnative -DskipTests        # native build (also leaves the JVM package)
#   scripts/mcp-native-parity.sh
#   JAR=... RUNNER=... PORT=... scripts/mcp-native-parity.sh
#
# Exit status: 0 when the two catalogues are byte-identical after canonicalisation, every
# tool carries annotations and every outputSchema declares at least one property; 1
# otherwise, with the diff on stderr.
#
# Both servers are driven over the stateless 2026-07-28 protocol, which is what a modern
# client speaks. The shipped defaults are stdio on and HTTP off (a locally launched
# process), so both are flipped on the command line only: the check needs an HTTP port
# to ask, and a stdio transport reading a closed stdin would shut the server down.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JAR="${JAR:-$REPO_ROOT/target/quarkus-app/quarkus-run.jar}"
RUNNER="${RUNNER:-$(ls "$REPO_ROOT"/target/*-runner 2>/dev/null | head -1 || true)}"
PORT="${PORT:-9098}"
WORK_DIR="$(mktemp -d -t mcp-parity-XXXXXX)"

if [[ ! -f "$JAR" ]]; then
  echo "No JAR at $JAR -- build it first: ./mvnw package -DskipTests" >&2
  exit 1
fi
if [[ -z "$RUNNER" || ! -x "$RUNNER" ]]; then
  echo "No native executable at ${RUNNER:-target/*-runner} -- build it first: ./mvnw package -Pnative -DskipTests" >&2
  exit 1
fi

SERVER_PID=""
cleanup() {
  if [[ -n "$SERVER_PID" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

URL="http://127.0.0.1:$PORT/mcp"

# The stateless protocol carries the client's identity on every request instead of in a
# handshake. clientInfo and clientCapabilities are included because quarkus-mcp-server 2.0.0
# rejects the request without them.
META='"_meta":{"io.modelcontextprotocol/protocolVersion":"2026-07-28","io.modelcontextprotocol/clientInfo":{"name":"native-parity","version":"1"},"io.modelcontextprotocol/clientCapabilities":{}}'

rpc() {
  local method="$1"
  curl -sf -X POST "$URL" \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json, text/event-stream' \
    -H "Mcp-Method: $method" \
    -H 'MCP-Protocol-Version: 2026-07-28' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"$method\",\"params\":{$META}}"
}

# Starts one server, waits for it, records tools/list and how long start-up took.
#   $1  label (jvm | native)
#   $@  the command line
capture() {
  local label="$1"; shift
  local log="$WORK_DIR/$label.log"
  local started ready_at

  started=$(python3 -c 'import time; print(time.time())')
  "$@" > "$log" 2>&1 < /dev/null &
  SERVER_PID=$!

  local ready=""
  for _ in $(seq 1 600); do
    if ! kill -0 "$SERVER_PID" 2>/dev/null; then
      echo "[$label] exited before becoming ready:" >&2
      cat "$log" >&2
      exit 1
    fi
    if rpc server/discover > "$WORK_DIR/$label.discover.json" 2>/dev/null; then
      ready=yes
      break
    fi
    sleep 0.1
  done
  if [[ -z "$ready" ]]; then
    echo "[$label] did not become ready at $URL" >&2
    cat "$log" >&2
    exit 1
  fi
  ready_at=$(python3 -c 'import time; print(time.time())')

  rpc tools/list > "$WORK_DIR/$label.tools.raw.json"

  # Canonical form: sorted keys, fixed indentation. The two binaries serialise identically
  # today, but the comparison should not depend on that.
  python3 - "$WORK_DIR/$label.tools.raw.json" "$WORK_DIR/$label.tools.json" <<'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
with open(src) as f:
    doc = json.load(f)
with open(dst, "w") as f:
    json.dump(doc, f, indent=2, sort_keys=True)
    f.write("\n")
PY

  # What Quarkus itself measured, alongside the wall clock seen from outside.
  local reported
  reported=$(grep -o 'started in [0-9.]*s' "$log" | head -1 || true)
  python3 - "$label" "$started" "$ready_at" "$reported" <<'PY'
import sys
label, started, ready, reported = sys.argv[1], float(sys.argv[2]), float(sys.argv[3]), sys.argv[4]
print(f"[{label}] ready in {ready - started:.2f}s wall clock" + (f" ({reported})" if reported else ""))
PY

  kill "$SERVER_PID" 2>/dev/null || true
  wait "$SERVER_PID" 2>/dev/null || true
  SERVER_PID=""
}

COMMON_ARGS=(
  -Dquarkus.http.port="$PORT"
  -Dquarkus.http.host=127.0.0.1
  -Dquarkus.http.host-enabled=true
  -Dquarkus.mcp.server.stdio.enabled=false
  -Dquarkus.banner.enabled=false
  -Dquarkus.log.level=INFO
)

capture jvm java "${COMMON_ARGS[@]}" -jar "$JAR"
capture native "$RUNNER" "${COMMON_ARGS[@]}"

# An empty outputSchema is the failure this script exists to catch, so it is refused even
# when both binaries agree on it -- agreement on a broken catalogue is not parity worth having.
python3 - "$WORK_DIR/jvm.tools.json" "$WORK_DIR/native.tools.json" <<'PY'
import json, sys
failed = False
for path in sys.argv[1:]:
    with open(path) as f:
        tools = json.load(f)["result"]["tools"]
    if not tools:
        print(f"{path}: no tools published", file=sys.stderr)
        failed = True
    for tool in tools:
        schema = tool.get("outputSchema")
        if schema is None:
            print(f"{path}: {tool['name']} publishes no outputSchema", file=sys.stderr)
            failed = True
        elif not schema.get("properties"):
            print(f"{path}: {tool['name']} outputSchema has no properties: {json.dumps(schema)}", file=sys.stderr)
            failed = True
        if "annotations" not in tool:
            print(f"{path}: {tool['name']} publishes no annotations", file=sys.stderr)
            failed = True
sys.exit(1 if failed else 0)
PY

if diff -u "$WORK_DIR/jvm.tools.json" "$WORK_DIR/native.tools.json" >&2; then
  count=$(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["result"]["tools"]))' "$WORK_DIR/jvm.tools.json")
  bytes=$(wc -c < "$WORK_DIR/jvm.tools.json" | tr -d ' ')
  echo "tools/list is identical on JVM and native: $count tools, $bytes bytes of canonical JSON"
else
  echo "tools/list differs between JVM and native (see diff above)" >&2
  exit 1
fi
