#!/usr/bin/env bash
#
# Proves that the native executable publishes the same tool catalogue as the JVM build.
#
# Why this exists: a native image can lose part of the catalogue without failing. The
# outputSchema of every tool is generated by reflection over the @OutputSchema(from=...)
# records, and a record the native image does not know about yields `{"type":"object"}` --
# a valid schema, an empty one, and no error anywhere. A client that validates
# structuredContent then accepts anything, and a typed SDK gets no fields to type. The
# only way to see it is to ask both binaries and compare.
#
# Usage:
#   ./mvnw package -DskipTests                 # JVM build
#   ./mvnw package -Pnative -DskipTests        # native build (also leaves the JVM package)
#   scripts/mcp-native-parity.sh
#   JAR=... RUNNER=... PORT=... scripts/mcp-native-parity.sh
#
# It also calls two tools on each binary against a local stand-in of the landscape
# (python3 http.server serving src/test/resources/landscape-current.json) and requires the
# same structuredContent from both. tools/list cannot see a class the native image dropped
# but a tool needs at call time -- Caffeine's cache nodes, chosen by name at runtime, failed
# exactly that way once: catalogue identical, every call "Internal error".
#
# Exit status: 0 when the two catalogues are byte-identical after canonicalisation, every
# tool carries annotations, every outputSchema declares at least one property and both
# binaries answer the two tool calls identically; 1 otherwise, with the diff on stderr.
#
# Both servers are driven over the stateless 2026-07-28 protocol, which is what a modern
# client speaks. The shipped defaults are stdio on and HTTP off (a locally launched
# process), so both are flipped on the command line only: the check needs an HTTP port
# to ask, and a stdio transport reading a closed stdin would shut the server down.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JAR="${JAR:-$REPO_ROOT/target/quarkus-app/quarkus-run.jar}"
RUNNER="${RUNNER:-$(ls "$REPO_ROOT"/target/*-runner 2>/dev/null | head -1 || true)}"
PORT="${PORT:-9098}"
WORK_DIR="$(mktemp -d -t mcp-parity-XXXXXX)"

if [[ ! -f "$JAR" ]]; then
  echo "No JAR at $JAR -- build it first: ./mvnw package -DskipTests" >&2
  exit 1
fi
if [[ -z "$RUNNER" || ! -x "$RUNNER" ]]; then
  echo "No native executable at ${RUNNER:-target/*-runner} -- build it first: ./mvnw package -Pnative -DskipTests" >&2
  exit 1
fi

SERVER_PID=""
STUB_PID=""
cleanup() {
  for pid in "$SERVER_PID" "$STUB_PID"; do
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
    fi
  done
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

# A stand-in for landscape.cncf.io: the test fixture at /data/full.json, nothing else. The
# fixture's clock placeholders are filled the way LandscapeStub does, so both binaries see
# the same bytes and the "actively maintained" flag is deterministic.
STUB_PORT="${STUB_PORT:-9099}"
mkdir -p "$WORK_DIR/stub/data"
python3 - "$REPO_ROOT/src/test/resources/landscape-current.json" "$WORK_DIR/stub/data/full.json" <<'PY'
import sys, datetime
src, dst = sys.argv[1], sys.argv[2]
now = datetime.datetime.now(datetime.timezone.utc)
iso = lambda d: d.strftime("%Y-%m-%dT%H:%M:%SZ")
text = open(src).read().replace("__RECENT_COMMIT__", iso(now - datetime.timedelta(days=1))) \
                       .replace("__STALE_COMMIT__", iso(now - datetime.timedelta(days=400)))
open(dst, "w").write(text)
PY
python3 -m http.server "$STUB_PORT" --bind 127.0.0.1 --directory "$WORK_DIR/stub" > "$WORK_DIR/stub.log" 2>&1 &
STUB_PID=$!

URL="http://127.0.0.1:$PORT/mcp"

# The stateless protocol carries the client's identity on every request instead of in a
# handshake. clientInfo and clientCapabilities are included because quarkus-mcp-server 2.0.0
# rejects the request without them.
META='"_meta":{"io.modelcontextprotocol/protocolVersion":"2026-07-28","io.modelcontextprotocol/clientInfo":{"name":"native-parity","version":"1"},"io.modelcontextprotocol/clientCapabilities":{}}'

rpc() {
  local method="$1"
  curl -sf -X POST "$URL" \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json, text/event-stream' \
    -H "Mcp-Method: $method" \
    -H 'MCP-Protocol-Version: 2026-07-28' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"$method\",\"params\":{$META}}"
}

# tools/call over the stateless protocol: the tool name travels in Mcp-Name as well.
call_tool() {
  local tool="$1" args="$2"
  curl -sf -X POST "$URL" \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json, text/event-stream' \
    -H 'Mcp-Method: tools/call' \
    -H "Mcp-Name: $tool" \
    -H 'MCP-Protocol-Version: 2026-07-28' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"$tool\",\"arguments\":$args,$META}}"
}

# Starts one server, waits for it, records tools/list and how long start-up took.
#   $1  label (jvm | native)
#   $@  the command line
capture() {
  local label="$1"; shift
  local log="$WORK_DIR/$label.log"
  local started ready_at

  started=$(python3 -c 'import time; print(time.time())')
  "$@" > "$log" 2>&1 < /dev/null &
  SERVER_PID=$!

  local ready=""
  for _ in $(seq 1 600); do
    if ! kill -0 "$SERVER_PID" 2>/dev/null; then
      echo "[$label] exited before becoming ready:" >&2
      cat "$log" >&2
      exit 1
    fi
    if rpc server/discover > "$WORK_DIR/$label.discover.json" 2>/dev/null; then
      ready=yes
      break
    fi
    sleep 0.1
  done
  if [[ -z "$ready" ]]; then
    echo "[$label] did not become ready at $URL" >&2
    cat "$log" >&2
    exit 1
  fi
  ready_at=$(python3 -c 'import time; print(time.time())')

  rpc tools/list > "$WORK_DIR/$label.tools.raw.json"

  # Two calls that exercise the download, the parser, the sanitizer, the fence and the
  # rate limiter -- the code paths tools/list never touches.
  {
    call_tool list_cncf_categories '{}'
    echo
    call_tool search_cncf '{"query":"kube","limit":3}'
  } > "$WORK_DIR/$label.calls.raw.json"
  python3 - "$WORK_DIR/$label.calls.raw.json" "$WORK_DIR/$label.calls.json" "$label" <<'PY'
import json, sys
src, dst, label = sys.argv[1], sys.argv[2], sys.argv[3]
out = []
for line in open(src):
    line = line.strip()
    if not line:
        continue
    doc = json.loads(line)
    if "result" not in doc or doc["result"].get("isError"):
        print(f"[{label}] tool call failed: {json.dumps(doc)[:300]}", file=sys.stderr)
        sys.exit(1)
    # The text carries a per-response nonce; the structured record is what must match.
    out.append(doc["result"]["structuredContent"])
with open(dst, "w") as f:
    json.dump(out, f, indent=2, sort_keys=True)
    f.write("\n")
PY

  # Canonical form: sorted keys, fixed indentation. The two binaries serialise identically
  # today, but the comparison should not depend on that.
  python3 - "$WORK_DIR/$label.tools.raw.json" "$WORK_DIR/$label.tools.json" <<'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
with open(src) as f:
    doc = json.load(f)
with open(dst, "w") as f:
    json.dump(doc, f, indent=2, sort_keys=True)
    f.write("\n")
PY

  # What Quarkus itself measured, alongside the wall clock seen from outside.
  local reported
  reported=$(grep -o 'started in [0-9.]*s' "$log" | head -1 || true)
  python3 - "$label" "$started" "$ready_at" "$reported" <<'PY'
import sys
label, started, ready, reported = sys.argv[1], float(sys.argv[2]), float(sys.argv[3]), sys.argv[4]
print(f"[{label}] ready in {ready - started:.2f}s wall clock" + (f" ({reported})" if reported else ""))
PY

  kill "$SERVER_PID" 2>/dev/null || true
  wait "$SERVER_PID" 2>/dev/null || true
  SERVER_PID=""
}

COMMON_ARGS=(
  -Dquarkus.http.port="$PORT"
  -Dquarkus.http.host=127.0.0.1
  -Dquarkus.http.host-enabled=true
  -Dquarkus.mcp.server.stdio.enabled=false
  -Dquarkus.banner.enabled=false
  -Dquarkus.log.level=INFO
  -Dcncf.landscape.base-url="http://127.0.0.1:$STUB_PORT"
  -Dcncf.landscape.request-timeout=PT5S
)

capture jvm java "${COMMON_ARGS[@]}" -jar "$JAR"
capture native "$RUNNER" "${COMMON_ARGS[@]}"

# An empty outputSchema is the failure this script exists to catch, so it is refused even
# when both binaries agree on it -- agreement on a broken catalogue is not parity worth having.
python3 - "$WORK_DIR/jvm.tools.json" "$WORK_DIR/native.tools.json" <<'PY'
import json, sys
failed = False
for path in sys.argv[1:]:
    with open(path) as f:
        tools = json.load(f)["result"]["tools"]
    if not tools:
        print(f"{path}: no tools published", file=sys.stderr)
        failed = True
    for tool in tools:
        schema = tool.get("outputSchema")
        if schema is None:
            print(f"{path}: {tool['name']} publishes no outputSchema", file=sys.stderr)
            failed = True
        elif not schema.get("properties"):
            print(f"{path}: {tool['name']} outputSchema has no properties: {json.dumps(schema)}", file=sys.stderr)
            failed = True
        if "annotations" not in tool:
            print(f"{path}: {tool['name']} publishes no annotations", file=sys.stderr)
            failed = True
sys.exit(1 if failed else 0)
PY

if ! diff -u "$WORK_DIR/jvm.tools.json" "$WORK_DIR/native.tools.json" >&2; then
  echo "tools/list differs between JVM and native (see diff above)" >&2
  exit 1
fi
if ! diff -u "$WORK_DIR/jvm.calls.json" "$WORK_DIR/native.calls.json" >&2; then
  echo "tools/call results differ between JVM and native (see diff above)" >&2
  exit 1
fi
count=$(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["result"]["tools"]))' "$WORK_DIR/jvm.tools.json")
bytes=$(wc -c < "$WORK_DIR/jvm.tools.json" | tr -d ' ')
projects=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))[0]["totalProjects"])' "$WORK_DIR/jvm.calls.json")
echo "tools/list is identical on JVM and native: $count tools, $bytes bytes of canonical JSON"
echo "tools/call is identical on JVM and native: list_cncf_categories and search_cncf over a $projects-project stub"
